default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: crest_development

test:
  <<: *default
  database: crest_test

production:
  <<: *default
  database: crest_production
